name: ai4foodsecurity
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pandas==1.0.1
  - geopandas==0.8.2
  - rasterio==1.1.8
  - matplotlib==3.3.2
  - tensorboard==2.4.0
  - sentinelhub==3.3.2
  - pytorch==1.9.0
  - torchvision==0.10.0
  - numpy==1.19.5
  - sh==1.14.2
  - radiant-mlhub==0.3.0
  # platform basic requirement
  - ipykernel=5.3.4

  - 'cudatoolkit=11.1'
  - pip
    # have to see if the above works on the vader nodes
    #- pytorch
    #- torchvision
    #- torchaudio

  - pip:
    # edc
    # NOTE: it's probably ok to update these further in the future
    - eo-learn==0.9.1  # available on conda, but not latest version
    - sentinelhub==3.3.2  # available on conda, but not latest version
    - breizhcrops==0.0.2.8
    - nni==2.3

    # install via pip because according to iot-salzburg/gpu-jupyter conda install leads to errors
    # have to see if the above works on the vader nodes
    #- torch==1.9.0+cu111
    #- torchvision==0.10.0+cu111
    #- torchaudio==0.9.0
